// AUTO-GENERATED by scripts/generate-changelog.cjs — do not edit manually.
// Regenerates on every `npm run build` and `npm run dev` via npm lifecycle hooks.

export interface ChangeEntry {
  version: string;
  date: string;
  highlights: string[];
}

export const RECENT_CHANGES: ChangeEntry[] = [
  {
    "version": "2.2.0",
    "date": "May 26, 2026",
    "highlights": [
      "Shopping item assignment",
      "Shopping item notes",
      "Multi-store layout profiles",
      "In-app account deletion"
    ]
  },
  {
    "version": "2.1.6",
    "date": "May 26, 2026",
    "highlights": [
      "Camera scan timeout — handleTakePhoto was setting the loading state to LOADING before the OS camera opened, causing…",
      "`customCategories` consolidated onto user doc — custom pantry categories are now stored as a field on users/{uid}…",
      "Stripe packages removed — stripe, @stripe/react-stripe-js, and @stripe/stripe-js were unused and have been uninstalled",
      "Dependencies updated — all patch/minor versions bumped (@capacitor/* 8.3.4, firebase 12.13.0, react/react-dom 19.2.6,…"
    ]
  }
];
