// AUTO-GENERATED by scripts/generate-changelog.cjs — do not edit manually.
// Regenerates on every `npm run build` and `npm run dev` via npm lifecycle hooks.

export interface ChangeEntry {
  version: string;
  date: string;
  highlights: string[];
}

export const RECENT_CHANGES: ChangeEntry[] = [
  {
    "version": "2.4.7",
    "date": "Jun 16, 2026",
    "highlights": [
      "Leave Household for Solo Admins — Enabled the \"Leave Household\" button for admins who are the only member in their…",
      "Unified Household UI — Cleaned up massive amounts of duplicate and dead layout code in the Household Management…"
    ]
  },
  {
    "version": "2.4.6",
    "date": "Jun 16, 2026",
    "highlights": [
      "Offline Recipe Classification — Added rule-based keyword classification script (classify-recipes-rules.js) and…",
      "Firestore Listener Optimization — Introduced a global SubscriptionContext and SubscriptionProvider to establish…",
      "Meal Planner Auto-Fill — Updated auto-fill algorithm to strictly exclude recipes containing allergy-violating…",
      "Popular Recipes Search — Integrated allergy screening and preference ranking into the popular recipes search modal…"
    ]
  },
  {
    "version": "2.4.5",
    "date": "Jun 16, 2026",
    "highlights": [
      "Meal Planner Auto-Fill",
      "Gemini Token Debugger",
      "Single-Member Household Deletion",
      "Cache Data Preservation"
    ]
  }
];
