// AUTO-GENERATED by scripts/generate-product-tier-map.cjs from constants/productTierMap.json
// - do not edit manually. See .claude/audits/FIXES.md F63.

export const PRODUCT_TIER_MAP: Record<string, 'premium' | 'family'> = {
  "premium_monthly": "premium",
  "premium_yearly": "premium",
  "family_monthly": "family",
  "family_yearly": "family"
};
