import React, { useMemo } from 'react';
import { ShoppingBasket, Check, Trash2, Archive, Plus, X, Share2, Copy, Download, MessageSquare } from 'lucide-react';
import { ShoppingItem } from '../types';
import { inferCategoryFromItemName, getItemImage } from '../utils/appUtils';

interface ShoppingListProps {
  items: ShoppingItem[];
  setItems: React.Dispatch<React.SetStateAction<ShoppingItem[]>>;
  onMoveToPantry: (items: ShoppingItem[]) => void;
}

export const ShoppingList: React.FC<ShoppingListProps> = ({ items, setItems, onMoveToPantry }) => {
  const [newItem, setNewItem] = React.useState('');
  const [newQty, setNewQty] = React.useState<string>('1');
  const [isAddModalOpen, setIsAddModalOpen] = React.useState(false);

  // Suggested items for quick adding
  const suggestedItems = [
    'Milk', 'Bread', 'Eggs', 'Cheese', 'Bananas', 'Apples', 'Chicken', 'Pasta', 
    'Rice', 'Tomatoes', 'Lettuce', 'Onions', 'Potatoes', 'Carrots', 'Butter', 'Yogurt'
  ];

  // Memoized expensive computations for sharing/exporting
  const uncheckedItemsText = useMemo(() => 
    items
      .filter(item => !item.checked)
      .map(item => `${item.item}${item.quantity && item.quantity !== '1' ? ` (${item.quantity})` : ''}`)
      .join('\n'),
    [items]
  );

  const shoppingListExportText = useMemo(() => 
    `Shopping List\n${'='.repeat(20)}\n\n${items
      .filter(item => !item.checked)
      .map(item => `□ ${item.item}${item.quantity && item.quantity !== '1' ? ` (${item.quantity})` : ''}`)
      .join('\n')}\n\nGenerated by Smart Pantry Chef`,
    [items]
  );

  const smsMessageText = useMemo(() => 
    `Shopping List:\n${uncheckedItemsText}\n\nSent from Smart Pantry Chef`,
    [uncheckedItemsText]
  );

  const addSuggestedItem = (itemName: string) => {
    // Check if item already exists
    const exists = items.some(item => item.item.toLowerCase() === itemName.toLowerCase());
    if (exists) {
      alert(`${itemName} is already in your shopping list!`);
      return;
    }

    setItems(prev => [...prev, {
      id: Math.random().toString(36).substr(2, 9),
      item: itemName,
      category: inferCategoryFromItemName(itemName),
      checked: false,
      quantity: '1',
      source: 'suggested'
    }]);
  };

  const addRecipeItem = (itemName: string, requiredQuantity: string, recipeName: string) => {
    // Check if item already exists
    const existingItem = items.find(item => item.item.toLowerCase() === itemName.toLowerCase());
    if (existingItem) {
      // Update the existing item with recipe info if it doesn't already have it
      if (!existingItem.source || !existingItem.source.includes('recipe')) {
        setItems(prev => prev.map(item => 
          item.id === existingItem.id 
            ? { ...item, source: `recipe: ${recipeName} (${requiredQuantity})` }
            : item
        ));
      }
      return;
    }

    setItems(prev => [...prev, {
      id: Math.random().toString(36).substr(2, 9),
      item: itemName,
      category: inferCategoryFromItemName(itemName),
      checked: false,
      quantity: requiredQuantity,
      source: `recipe: ${recipeName}`
    }]);
  };

  const toggleCheck = (id: string) => {
    setItems(prev => prev.map(i => i.id === id ? { ...i, checked: !i.checked } : i));
  };

  const selectAll = () => {
    setItems(prev => prev.map(i => ({ ...i, checked: true })));
  };

  const deselectAll = () => {
    setItems(prev => prev.map(i => ({ ...i, checked: false })));
  };

  const remove = (id: string) => {
    setItems(prev => prev.filter(i => i.id !== id));
  };

  const addItem = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newItem.trim() || !newQty.trim()) return;
    setItems(prev => [...prev, {
        id: Math.random().toString(36).substr(2, 9),
        item: newItem,
        category: inferCategoryFromItemName(newItem),
        checked: false,
        quantity: newQty,
        source: 'manual'
    }]);
    setNewItem('');
    setNewQty('1');
    setIsAddModalOpen(false); // Close modal after adding
  };

  const closeModal = () => {
    setIsAddModalOpen(false);
    setNewItem('');
    setNewQty('1');
  };

  const handleCheckout = () => {
    const purchased = items.filter(i => i.checked);
    if (purchased.length === 0) return;
    
    // Set default purchased quantities for items that don't have them
    const updatedItems = purchased.map(item => {
      if (!item.purchasedQuantity) {
        // Try to parse the needed quantity, default to 1 count
        const neededQty = item.quantity ? parseFloat(item.quantity) : 1;
        return { ...item, purchasedQuantity: { amount: neededQty, unit: 'count' } };
      }
      return item;
    });
    
    if (confirm(`Move ${purchased.length} items to pantry?`)) {
        onMoveToPantry(updatedItems);
        setItems(prev => prev.filter(i => !i.checked));
    }
  };

  const handleCopyToClipboard = () => {
    navigator.clipboard.writeText(uncheckedItemsText).then(() => {
      alert('Shopping list copied to clipboard!');
    }).catch(err => {
      console.error('Failed to copy: ', err);
      alert('Failed to copy to clipboard');
    });
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Shopping List',
          text: uncheckedItemsText
        });
      } catch (err) {
        console.log('Share cancelled or failed');
      }
    } else {
      // Fallback to clipboard
      handleCopyToClipboard();
    }
  };

  const handleExport = () => {
    const blob = new Blob([shoppingListExportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'shopping-list.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleShareViaSMS = () => {
    // Use sms: protocol to open default SMS app
    const smsUrl = `sms:?body=${encodeURIComponent(smsMessageText)}`;
    
    // Try to open SMS app
    window.open(smsUrl, '_blank');
    
    // Fallback: copy to clipboard if SMS app doesn't open
    setTimeout(() => {
      navigator.clipboard.writeText(smsMessageText).then(() => {
        alert('Shopping list copied to clipboard (SMS app may not be available)');
      }).catch(() => {
        alert('Unable to open SMS app. Shopping list has been copied to clipboard.');
      });
    }, 1000);
  };

  return (
    <div className="space-y-6 pb-24 max-w-2xl mx-auto animate-fade-in relative">
      <div className="text-center mb-6">
        <h2 className="text-3xl font-serif font-bold text-theme-secondary">Shopping List</h2>
        <p className="text-theme-secondary opacity-60 text-sm mt-1">Items to purchase</p>
        
        {/* Export/Share Buttons */}
        {items.length > 0 && (
          <div className="flex justify-center gap-2 mt-4 flex-wrap">
            <button
              onClick={handleCopyToClipboard}
              className="flex items-center gap-2 px-3 py-2 bg-theme-secondary text-theme-primary rounded-lg border border-theme hover:bg-theme-primary transition-colors text-sm"
              title="Copy to clipboard"
            >
              <Copy className="w-4 h-4" />
              Copy
            </button>
            <button
              onClick={handleShare}
              className="flex items-center gap-2 px-3 py-2 bg-theme-secondary text-theme-primary rounded-lg border border-theme hover:bg-theme-primary transition-colors text-sm"
              title="Share shopping list"
            >
              <Share2 className="w-4 h-4" />
              Share
            </button>
            <button
              onClick={handleShareViaSMS}
              className="flex items-center gap-2 px-3 py-2 bg-theme-secondary text-theme-primary rounded-lg border border-theme hover:bg-theme-primary transition-colors text-sm"
              title="Send via text message"
            >
              <MessageSquare className="w-4 h-4" />
              SMS
            </button>
            <button
              onClick={handleExport}
              className="flex items-center gap-2 px-3 py-2 bg-theme-secondary text-theme-primary rounded-lg border border-theme hover:bg-theme-primary transition-colors text-sm"
              title="Download as text file"
            >
              <Download className="w-4 h-4" />
              Export
            </button>
          </div>
        )}
      </div>

      {/* Suggested Items */}
      <div className="bg-theme-secondary rounded-xl p-4 border border-theme">
        <h3 className="text-sm font-semibold text-theme-primary mb-3 flex items-center gap-2">
          <Plus className="w-4 h-4" />
          Quick Add Suggestions
        </h3>
        <div className="flex gap-3 overflow-x-auto pb-2 scrollbar-hide flex-nowrap">
          {suggestedItems.map((itemName) => (
            <button
              key={itemName}
              onClick={() => addSuggestedItem(itemName)}
              className="flex-shrink-0 flex flex-col items-center gap-2 p-3 bg-theme-primary rounded-lg border border-theme hover:border-[var(--accent-color)] hover:bg-[var(--accent-color)]/5 transition-all group min-w-[80px]"
            >
              <img
                src={getItemImage(itemName, inferCategoryFromItemName(itemName))}
                alt={itemName}
                className="w-10 h-10 rounded-lg object-cover bg-theme-secondary border border-theme"
                onError={(e) => {
                  const target = e.target as HTMLImageElement;
                  target.src = '/images/placeholder.svg';
                }}
              />
              <span className="text-xs font-medium text-theme-primary text-center leading-tight group-hover:text-[var(--accent-color)] transition-colors">
                {itemName}
              </span>
            </button>
          ))}
        </div>
      </div>

      {/* Floating Action Button */}
      <button
        onClick={() => setIsAddModalOpen(true)}
        className="fixed bottom-28 right-6 z-50 bg-[var(--accent-color)] text-white p-4 rounded-full shadow-lg hover:shadow-xl transition-all duration-300 hover:scale-110"
        style={{ bottom: 'calc(7rem + 15px)' }}
        aria-label="Add items to shopping list"
      >
        <Plus className="w-6 h-6" />
      </button>

      {/* Add Items Modal */}
      {isAddModalOpen && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-end justify-center p-4">
          <div className="bg-theme-primary rounded-t-3xl max-w-md w-full max-h-[80vh] overflow-y-auto shadow-xl animate-slide-up">
            <div className="p-6 pb-2.5">
              <div className="flex items-center justify-between mb-6">
                <h3 className="text-xl font-bold text-theme-secondary">Add to Shopping List</h3>
                <button
                  onClick={closeModal}
                  className="p-2 hover:bg-theme-secondary rounded-full transition-colors"
                >
                  <X className="w-5 h-5 text-theme-secondary" />
                </button>
              </div>

              <form onSubmit={addItem} className="space-y-4">
                <div className="space-y-4">
                  <input 
                    id="newItem"
                    name="newItem"
                    type="text"
                    value={newItem}
                    onChange={(e) => setNewItem(e.target.value)}
                    placeholder="Enter item name..."
                    className="w-full bg-theme-secondary border border-theme rounded-lg px-4 py-3 text-theme-primary shadow-sm outline-none focus:border-[var(--accent-color)]"
                    autoFocus
                  />
                  <div className="flex gap-3">
                    <input
                      id="newQty"
                      name="newQty"
                      type="text"
                      value={newQty}
                      onChange={e => setNewQty(e.target.value)}
                      className="flex-1 bg-theme-secondary border border-theme rounded-lg px-3 py-3 text-theme-primary shadow-sm focus:border-[var(--accent-color)] outline-none"
                      placeholder="Quantity (e.g. 2, 1 cup, 2 tbsp)"
                    />
                  </div>
                </div>
                <button 
                  type="submit" 
                  className="w-full py-3 rounded-lg font-bold text-sm uppercase tracking-wider flex items-center justify-center gap-2 bg-[var(--accent-color)] text-white shadow-lg hover:bg-[var(--accent-color)]/90 transition-colors"
                >
                  <Plus className="w-4 h-4" />
                  Add Item
                </button>
              </form>
            </div>
          </div>
        </div>
      )}

      {items.length > 0 && (
          <div className="flex gap-2 justify-between">
              <button
                onClick={items.every(i => i.checked) ? deselectAll : selectAll}
                className="flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-bold uppercase tracking-wider transition-all bg-theme-secondary text-theme-secondary hover:bg-[var(--accent-color)] hover:text-white"
              >
                  <Check className="w-4 h-4" /> 
                  {items.every(i => i.checked) ? 'Deselect All' : 'Select All'}
              </button>
              <button 
                onClick={handleCheckout}
                disabled={!items.some(i => i.checked)}
                className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-bold uppercase tracking-wider transition-all ${
                    items.some(i => i.checked) 
                    ? 'bg-[var(--accent-color)] text-white shadow-lg' 
                    : 'bg-theme-secondary text-theme-secondary opacity-50 cursor-not-allowed'
                }`}
              >
                  <Archive className="w-4 h-4" /> Move Checked to Pantry
              </button>
          </div>
      )}

      <div className="space-y-2">
        {items.map((item) => (
          <div 
            key={item.id} 
            onClick={() => toggleCheck(item.id)}
            className={`flex items-center justify-between p-3 rounded-xl border transition-all cursor-pointer group ${
              item.checked 
              ? 'bg-[var(--accent-color)]/10 border-[var(--accent-color)]/30' 
              : 'bg-theme-secondary border-theme hover:border-[var(--accent-color)]/50'
            }`}
          >
            <div className="flex items-center gap-3 flex-1">
              <div className={`w-5 h-5 rounded-full border-2 flex items-center justify-center transition-all ${
                item.checked ? 'bg-[var(--accent-color)] border-[var(--accent-color)]' : 'border-theme'
              }`}>
                {item.checked && <Check className="w-3 h-3 text-white" />}
              </div>
              <div className="flex-1">
                <span className={`font-medium ${item.checked ? 'line-through opacity-50' : 'text-theme-primary'}`}>
                  {item.item}
                </span>
                {item.source && (
                  <div className="text-xs text-theme-secondary opacity-60 mt-1">
                    {item.source === 'suggested' && '💡 Suggested item'}
                    {item.source === 'manual' && '✏️ Manually added'}
                    {item.source === 'meal planner' && '📅 From meal planner'}
                    {item.source === 'pantry scanner' && '📷 From pantry scanner'}
                    {item.source === 'scanner suggestion' && '🤖 Scanner suggestion'}
                    {item.source?.startsWith('recipe:') && `🍳 ${item.source.substring(8)}`}
                  </div>
                )}
                {item.quantity && item.quantity !== '1' && (
                  <div className="text-xs text-theme-secondary opacity-70">Needed: {item.quantity}</div>
                )}
                {item.checked && (
                  <div className="mt-2">
                    <select
                      value={item.purchasedQuantity ? `${item.purchasedQuantity.amount} ${item.purchasedQuantity.unit}` : ''}
                      onChange={(e) => {
                        e.stopPropagation();
                        const [amount, unit] = e.target.value.split(' ');
                        setItems(prev => prev.map(i => 
                          i.id === item.id 
                            ? { ...i, purchasedQuantity: { amount: parseFloat(amount), unit } }
                            : i
                        ));
                      }}
                      onClick={(e) => e.stopPropagation()}
                      className="text-xs bg-theme-primary border border-theme rounded px-2 py-1 text-theme-primary"
                    >
                      <option value="">Select purchased quantity</option>
                      {/* Common quantity options based on item type */}
                      {item.item.toLowerCase().includes('milk') && (
                        <>
                          <option value="0.5 gal">½ gallon</option>
                          <option value="1 gal">1 gallon</option>
                          <option value="2 gal">2 gallons</option>
                        </>
                      )}
                      {(item.item.toLowerCase().includes('meat') || item.item.toLowerCase().includes('chicken') || item.item.toLowerCase().includes('beef') || item.item.toLowerCase().includes('pork')) && (
                        <>
                          <option value="0.5 lb">½ lb</option>
                          <option value="1 lb">1 lb</option>
                          <option value="2 lb">2 lbs</option>
                          <option value="3 lb">3 lbs</option>
                        </>
                      )}
                      {(item.item.toLowerCase().includes('bread') || item.item.toLowerCase().includes('loaf')) && (
                        <>
                          <option value="1 loaf">1 loaf</option>
                          <option value="2 loaf">2 loaves</option>
                        </>
                      )}
                      {(item.item.toLowerCase().includes('egg') || item.item.toLowerCase().includes('eggs')) && (
                        <>
                          <option value="6 count">6 eggs</option>
                          <option value="12 count">12 eggs</option>
                          <option value="18 count">18 eggs</option>
                          <option value="24 count">24 eggs</option>
                        </>
                      )}
                      {/* Generic options */}
                      <option value="1 count">1 item</option>
                      <option value="2 count">2 items</option>
                      <option value="3 count">3 items</option>
                      <option value="6 count">6 items</option>
                      <option value="12 count">12 items</option>
                    </select>
                  </div>
                )}
              </div>
            </div>
            <div className="flex items-center gap-2">
              {item.quantity && item.quantity !== '1' && (
                <div className="text-xs font-medium text-theme-secondary opacity-70 bg-theme-primary px-2 py-1 rounded">
                  {item.quantity}
                </div>
              )}
              <button 
                onClick={(e) => { e.stopPropagation(); remove(item.id); }}
                className="p-2 text-theme-secondary opacity-30 hover:opacity-100 hover:text-red-500 transition-opacity"
              >
                <Trash2 className="w-4 h-4" />
              </button>
            </div>
          </div>
        ))}
        {items.length === 0 && (
             <div className="text-center py-12 opacity-30 flex flex-col items-center">
                <ShoppingBasket className="w-12 h-12 mb-2" />
                <p>List is empty</p>
             </div>
        )}
      </div>
    </div>
  );
};