"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.wrapImpactTrackingUrl = exports.sendDailyReminders = exports.sendPushNotificationOnWrite = exports.retryPendingAccountDeletions = exports.deleteAccount = exports.handlePlaySubscriptionNotification = exports.verifyPurchase = exports.checkExpiredSubscriptions = exports.resetWeeklyUsageLimits = exports.getNutritionData = exports.migrateHouseholdClaims = exports.acceptInvitation = exports.checkInvitation = exports.removeHouseholdMember = exports.leaveHousehold = exports.inviteMember = void 0;
const v2_1 = require("firebase-functions/v2");
(0, v2_1.setGlobalOptions)({ region: "us-east1" });
var inviteMember_1 = require("./inviteMember");
Object.defineProperty(exports, "inviteMember", { enumerable: true, get: function () { return inviteMember_1.inviteMember; } });
var leaveHousehold_1 = require("./leaveHousehold");
Object.defineProperty(exports, "leaveHousehold", { enumerable: true, get: function () { return leaveHousehold_1.leaveHousehold; } });
var removeHouseholdMember_1 = require("./removeHouseholdMember");
Object.defineProperty(exports, "removeHouseholdMember", { enumerable: true, get: function () { return removeHouseholdMember_1.removeHouseholdMember; } });
var checkInvitation_1 = require("./checkInvitation");
Object.defineProperty(exports, "checkInvitation", { enumerable: true, get: function () { return checkInvitation_1.checkInvitation; } });
var acceptInvitation_1 = require("./acceptInvitation");
Object.defineProperty(exports, "acceptInvitation", { enumerable: true, get: function () { return acceptInvitation_1.acceptInvitation; } });
var migrateHouseholdClaims_1 = require("./migrateHouseholdClaims");
Object.defineProperty(exports, "migrateHouseholdClaims", { enumerable: true, get: function () { return migrateHouseholdClaims_1.migrateHouseholdClaims; } });
var nutrition_1 = require("./nutrition");
Object.defineProperty(exports, "getNutritionData", { enumerable: true, get: function () { return nutrition_1.getNutritionData; } });
var resetUsageLimits_1 = require("./resetUsageLimits");
Object.defineProperty(exports, "resetWeeklyUsageLimits", { enumerable: true, get: function () { return resetUsageLimits_1.resetWeeklyUsageLimits; } });
var checkExpiredSubscriptions_1 = require("./checkExpiredSubscriptions");
Object.defineProperty(exports, "checkExpiredSubscriptions", { enumerable: true, get: function () { return checkExpiredSubscriptions_1.checkExpiredSubscriptions; } });
var verifyPurchase_1 = require("./verifyPurchase");
Object.defineProperty(exports, "verifyPurchase", { enumerable: true, get: function () { return verifyPurchase_1.verifyPurchase; } });
var subscriptionNotifications_1 = require("./subscriptionNotifications");
Object.defineProperty(exports, "handlePlaySubscriptionNotification", { enumerable: true, get: function () { return subscriptionNotifications_1.handlePlaySubscriptionNotification; } });
var deleteAccount_1 = require("./deleteAccount");
Object.defineProperty(exports, "deleteAccount", { enumerable: true, get: function () { return deleteAccount_1.deleteAccount; } });
Object.defineProperty(exports, "retryPendingAccountDeletions", { enumerable: true, get: function () { return deleteAccount_1.retryPendingAccountDeletions; } });
var sendPushNotification_1 = require("./sendPushNotification");
Object.defineProperty(exports, "sendPushNotificationOnWrite", { enumerable: true, get: function () { return sendPushNotification_1.sendPushNotificationOnWrite; } });
var dailyReminders_1 = require("./dailyReminders");
Object.defineProperty(exports, "sendDailyReminders", { enumerable: true, get: function () { return dailyReminders_1.sendDailyReminders; } });
var impactTracking_1 = require("./impactTracking");
Object.defineProperty(exports, "wrapImpactTrackingUrl", { enumerable: true, get: function () { return impactTracking_1.wrapImpactTrackingUrl; } });
//# sourceMappingURL=index.js.map